# Generated by Django 6.0.4 on 2026-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_personaltraining_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltraining',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='personaltraining',
            name='status',
            field=models.CharField(choices=[('available', 'Доступна'), ('booked', 'Забронирована')], default='available', max_length=30, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='TrainingCancellation',
        ),
    ]
