# Generated by Django 6.0.4 on 2026-05-01 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('booked', 'Забронирована'), ('cancelled_by_trainer', 'Отменена тренером'), ('cancelled_by_client', 'Отменена клиентом'), ('completed', 'Завершена')], default='available', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_trainings', to='main.trainer')),
            ],
            options={
                'verbose_name': 'Персональная тренировка',
                'verbose_name_plural': 'Персональные тренировки',
            },
        ),
        migrations.CreateModel(
            name='TrainingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notified_users', models.ManyToManyField(related_name='cancellation_notifications', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='main.schedule')),
            ],
            options={
                'verbose_name': 'Отмена тренировки',
                'verbose_name_plural': 'Отмены тренировок',
            },
        ),
    ]
