# Generated by Django 6.0.4 on 2026-05-02 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltraining',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_trainings_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personaltraining',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'is_trainer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='personal_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
    ]
